### Chapter-2

Tensors


In [1]:
import torch

In [3]:
scalar = torch.tensor(5.0)
vector = torch.tensor([5.0, 8.0, 3.0])
matrix = torch.tensor([[1.0, 9.4, 2.2],
                      [4.9, 4.2, 2.0]])
tensor_3D = torch.tensor([

                    [[1,2,3],    # 2 matrix inside this
                     [1,2,3]],

                     [[8,2,3],
                     [3,2,7]]

                     ])


In [7]:
# filled tensors with known same values
zeros = torch.zeros(3,4)
ones = torch.ones(2,3)
any_value = torch.full((4, 5),3)
#torch.empty(row, col) allocate memory so use if overwrite right after
zeros, ones, any_value

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3]]))

In [ ]:
# filled ttensors with random values

uniform = torch.rand(4,6) # uniform dist between (0.0, 1.0)
normal = torch.randn(5, 7) # normal dist bell curve, unbounded
integers = torch.randint(0, 10, (3, 4)) # random value from 0-9
shuffled = torch.randperm(5)

uniform, normal, integers, shuffled

(tensor([[0.6138, 0.8100, 0.1280, 0.4221, 0.7397, 0.5555],
         [0.1538, 0.5363, 0.5795, 0.1404, 0.3854, 0.2943],
         [0.8012, 0.1316, 0.0673, 0.0926, 0.5336, 0.6650],
         [0.1041, 0.7395, 0.4160, 0.8103, 0.0702, 0.3469]]),
 tensor([[-0.9446, -1.1695, -1.0946,  0.4399,  0.4261,  0.1721,  0.2234],
         [-2.4482,  0.7752, -0.4240,  0.5085,  1.3159, -1.2432, -1.9006],
         [-1.0540,  0.0244, -0.6845, -0.5749,  0.8885, -0.4334,  0.0624],
         [-0.2823, -0.0293, -1.6942, -2.0670,  1.1429,  0.4693, -1.9283],
         [ 0.6180,  0.1907, -2.0425,  0.7324, -0.4496, -0.1699,  0.5006]]),
 tensor([[6, 7, 9, 0],
         [5, 4, 1, 2],
         [1, 1, 7, 6]]),
 tensor([3, 0, 4, 2, 1]))

In [16]:
# for reguler sequence

steps = torch.arange(0, 10, 2) # 0-9 with 2 step size
points = torch.linspace(0, 3, 5) # from 0-3 we divide it in 5 equal distant points

steps, points

(tensor([0, 2, 4, 6, 8]), tensor([0.0000, 0.7500, 1.5000, 2.2500, 3.0000]))

In [18]:
# the safeset way to copy from an existing tensor without sharing memory
x = torch.tensor([3.0, 2.99, 4.5])
copied = x.clone().detach()
x, copied

(tensor([3.0000, 2.9900, 4.5000]), tensor([3.0000, 2.9900, 4.5000]))

In [21]:
# for matching an existing tensors shape, dtype and device not values

device="cuda" if torch.cuda.is_available() else "cpu"
x = torch.randn(4, 7, device=device, dtype=torch.float64)

y = torch.zeros_like(x)
z = torch.randn_like(x)
x, y, z

(tensor([[ 1.6575,  0.4710, -0.3923, -1.0146,  2.1416, -1.5747, -0.6189],
         [-0.0557, -1.5734,  0.6973, -0.6353, -0.0780,  1.9923, -1.3327],
         [ 1.3389,  0.9098,  0.0974, -0.0832, -0.7695, -1.9284,  0.0773],
         [-0.0025,  1.0676,  0.1724,  0.9123,  0.1248, -0.7493, -0.8069]],
        device='cuda:0', dtype=torch.float64),
 tensor([[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]], device='cuda:0', dtype=torch.float64),
 tensor([[ 0.5679,  2.1366, -0.3194,  1.6878,  1.5130,  1.2866, -1.0542],
         [ 0.9565,  0.8506, -0.1137, -0.0463,  2.7760,  0.7855,  0.7003],
         [-0.6169,  1.7371, -0.2274, -0.4176, -1.1803,  1.9451,  0.7866],
         [-1.1512,  2.0508, -0.5125, -1.3334,  1.6853,  1.0842,  0.6680]],
        device='cuda:0', dtype=torch.float64))

In [ ]:
identity = torch.eye(4) # for identity matrix

diagonal = identity.diag() # get diagonal values of any tensor
rand_x = torch.randn(3,3)
rand_x_diag = rand_x.diag()

identity, diagonal, rand_x, rand_x_diag

(tensor([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]]),
 tensor([1., 1., 1., 1.]),
 tensor([[-0.0864,  1.0723, -0.2118],
         [-1.0595,  1.0138, -0.4076],
         [-0.1379,  0.5922,  0.7874]]),
 tensor([-0.0864,  1.0138,  0.7874]))

In [23]:
# ops doesn't work cross device tensors can't 

x = torch.tensor([3.3, 4.9], device="cuda")
y = torch.tensor([3.3, 4.9]) # here device by default "cpu"
z = x+y
z

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [30]:
# we can change dtype with tensor = tensor.to(type)
a = torch.tensor([1.3, 4.5], dtype=torch.float64)
print(a)
print(a.dtype)
a = a.to(torch.int32)
print(a)
print(a.dtype)

tensor([1.3000, 4.5000], dtype=torch.float64)
torch.float64
tensor([1, 4], dtype=torch.int32)
torch.int32


In [ ]:
# finding out storage taken by tensor
b = torch.tensor([
                [[1,2,3,4,5,6],
                [9,2,3,4,4,6]],

                [[1,2,3,4,5,6],
                [9,2,3,4,4,6]]
                ])

print(b.numel()) # total number of elements 2x2x6 = 24
print(b.dtype) # 64bits/8 = 8 bytes per item
print(b.element_size()) # byte size of every element
print(f"total bytes in the tensor: {b.numel()*b.element_size()} bytes")
print(b.untyped_storage().nbytes()) # Direct quired from the RAM

24
torch.int64
8
total bytes in the tensor: 192 bytes
192


In [ ]:
# torch.manual_seed(42) give use gloabl seed
# but for individial seed we should use generator
g1 = torch.Generator()
g1.manual_seed(42)
g2 = torch.Generator()
g2.manual_seed(42)
# g2.manual_seed(0) # will cause error


t1 = torch.randn(3,4, generator=g1)
t2 = torch.randn(3,4, generator=g2)

assert torch.equal(t1, t2)

In [ ]:
# pop out single ittem from single item tensors whatever dim
single_item_tensor = torch.tensor([[34]])
print(single_item_tensor.item())
print(single_item_tensor.item() == 34)

single_item_tensor_2 = torch.tensor([[[34]]])
print(single_item_tensor_2.item())
print(single_item_tensor_2.item() == 34)

# convert tensors to python list(but the float doesn't exactly convert)

tenten = torch.tensor([[1, 3, 4], [2, 9, 8]])
python_list = tenten.tolist()
print(python_list)
print(python_list == [[1, 3, 4], [2, 9, 8]])

#min and max for tensor return a tensor use .item() for pure value
print(tenten.min())
print(tenten.max())

print(tenten.min().item())
print(tenten.max().item())


34
True
34
True
[[1, 3, 4], [2, 9, 8]]
True
tensor(1)
tensor(9)
1
9


In [ ]:
# Equality

t1 = torch.tensor([0, 0, 0])
t2 = torch.tensor([0, 1, 0])

print(t1 == 0)
print(t2 == 0)
r = (t2 == 0).all() # check all
print(r)


print(torch.equal(t1, t2)) # checks identical shapes and values


tensor([True, True, True])
tensor([ True, False,  True])
tensor(False)
False


In [76]:
# check if a value is NaN or Inf

t1 = torch.zeros(3,2)
t2 = torch.ones(3,2)

print(t2/t1)
print(torch.isfinite(t2/t1))
print(torch.isfinite(t1/t2))

t3 = torch.ones(3,2, dtype=torch.float64)
t3[0][1] = float('nan')
print(t3)
print(torch.isfinite(t3))
print(torch.isfinite(t3).all())

tensor([[inf, inf],
        [inf, inf],
        [inf, inf]])
tensor([[False, False],
        [False, False],
        [False, False]])
tensor([[True, True],
        [True, True],
        [True, True]])
tensor([[1., nan],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[ True, False],
        [ True,  True],
        [ True,  True]])
tensor(False)


### A full worked example using the stuff above

In [77]:
# 1. Ensure reproducibility with an isolated generator:
g = torch.Generator()
g.manual_seed(42)

# 2. Tabular features: 1,000 samples with 4 continuous features:
X_tab = torch.randn(1000, 4, generator=g, dtype=torch.float32)

# 3. Categorical labels: 1,000 integer class IDs (0, 1, 2):
y_tab = torch.randint(0, 3, (1000,), generator=g, dtype=torch.int64)

# 4. Image batch: 16 color images (3 channels, 32x32 pixels):
images = torch.rand(16, 3, 32, 32, generator=g, dtype=torch.float32)

# 5. Dtype downcasting to save memory:
# Float32 uses 4 bytes per number. Float16 uses only 2 bytes!
images_fp16 = images.half()

# 6. Memory Audit:
# Theoretical bytes = numel() * element_size()
images_fp32_bytes = images.numel() * images.element_size()          # 16*3*32*32 * 4 = 196,608 bytes
images_fp16_bytes = images_fp16.numel() * images_fp16.element_size() # 16*3*32*32 * 2 = 98,304 bytes

assert images_fp32_bytes == images.untyped_storage().nbytes()
assert images_fp16_bytes == images_fp16.untyped_storage().nbytes()
assert images_fp16_bytes == images_fp32_bytes / 2  # Exactly 50% memory saved!

# 7. Move to target hardware:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
X_tab = X_tab.to(device)
y_tab = y_tab.to(device)
images_fp16 = images_fp16.to(device)

# 8. Sanity check dataset health:
assert torch.isfinite(X_tab).all()
assert torch.isfinite(images_fp16).all()
assert X_tab.device == y_tab.device == images_fp16.device

print(f"Dataset successfully created and audited on {device}!")
print(f"Images FP32 memory: {images_fp32_bytes / 1024:.1f} KB")
print(f"Images FP16 memory: {images_fp16_bytes / 1024:.1f} KB (50% reduction)")

Dataset successfully created and audited on cuda!
Images FP32 memory: 192.0 KB
Images FP16 memory: 96.0 KB (50% reduction)
