#### Chapter 2

In [1]:
import torch

In [ ]:
# reshape just change the shsape of the tensor
x = torch.arange(24)
print(x)
y = x.reshape(2, 3, 4)
print(y)
z = x.reshape(6, 4)
print(z)
# e = x.reshape(6, 5) error as 6x5 = 30 not 24
# print(e)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])


In [ ]:
# -1 trick for reshape
x = torch.arange(12)  
# "I want 4 rows, you figure out how many columns:"
y = x.reshape(4, -1)
print(y.shape)

# "I want 2 columns, you figure out how many rows:"
z = x.reshape(-1, 2)
print(z.shape)

torch.Size([4, 3])
torch.Size([6, 2])


In [10]:
# flatten sqash all dimension tot 1D

matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
print(matrix.shape)
flat = matrix.flatten()
print(flat.shape) # 3x2=6
print(flat)

torch.Size([2, 3])
torch.Size([6])
tensor([1, 2, 3, 4, 5, 6])


In [ ]:
# flatten with start_dim is more usefull
# suppose I have 8 color images 
# and it is needed to be passed on a linear layer whcih accept 1D Vector
image = torch.randn(8, 3, 32, 32)
print(image.shape)
# so 8 images and we want to make 3x32x32 into a 1D vector for each image
image_flatten = image.flatten(start_dim=1)
print(image_flatten.shape)

torch.Size([8, 3, 32, 32])
torch.Size([8, 3072])


In [14]:
# transpose is for swaping axis
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])  
print(x)
t = x.transpose(0, 1)  
print(t)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [15]:
# for 3D or 4D

x = torch.randn(32, 100, 64)  # Batch x Time x Features

# Some layers like 1D Convolution expect:- Batch x Features x Time
# We only want to swap Time (axis 1) and Features (axis 2)
y = x.transpose(1, 2)

print(y.shape)
# Axis 0 (Batch) stayed at position 0
# Axis 1 (Time) and Axis 2 (Features) swapped places

torch.Size([32, 64, 100])


In [16]:
# with transpose we can swap 2 axis but with t.permute() 
# we can swap all the axis at once

# PyTorch image: [Channel=3, Height=224, Width=224]
# Axis indices:    0           1           2
img_pytorch = torch.randn(3, 224, 224)

# We want: [Height, Width, Channel]
# New order: Axis 1, Axis 2, Axis 0
img_display = img_pytorch.permute(1, 2, 0)

print(img_display.shape) # now it is ready for plt.imshow()

torch.Size([224, 224, 3])


In [28]:
dm = torch.tensor([[[[3,4]]]])
dm.shape

torch.Size([1, 1, 1, 2])

In [29]:
# insert a 1 size dim to any index
t = torch.tensor([1,2,3])
t = t.unsqueeze(dim=1)
t

tensor([[1],
        [2],
        [3]])

In [ ]:
# squeeze remove 1 size dim
dm = dm.squeeze(dim=0)
print(dm.shape)
dm_all = dm.squeeze() # no dim so remove all 1 size dim 
print(dm_all.shape)

torch.Size([1, 1, 2])
torch.Size([2])


In [ ]:
# cat
a = torch.tensor([[ 1,  2,  3],
                  [ 4,  5,  6]]) 
b = torch.tensor([[ 7,  8,  9],
                  [10, 11, 12]]) 
row_cats = torch.cat([a, b], dim=0)
col_cats = torch.cat([a, b], dim=1)
print(row_cats)
print(col_cats)

stacked = torch.stack([a, b], dim=0)
print(stacked)
print(stacked.shape)

stacked_col = torch.stack([a, b], dim=1)
print(stacked_col)
print(stacked_col.shape)
# for stacked dim=1 we need to think like this
# a = torch.tensor([[ 1,  2,  3], [ 4,  5,  6]]) 
# b = torch.tensor([[ 7,  8,  9], [10, 11, 12]]) 
# column wise new dimension like unsqueeze tthen cat column wise

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 2, 3])
tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]])
torch.Size([2, 2, 3])


In [40]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])
# Sample std (divides by N - 1 = 4):
sample_std = x.std(correction=1) 
print(sample_std)
# Population std (divides by N = 5):
pop_std = x.std(correction=0)   
print(pop_std)

tensor(1.5811)
tensor(1.4142)


In [41]:
x = torch.tensor([-5.0, -1.0, 0.0, 0.5, 3.0, 10.0])

# Everything below 0 becomes 0, everything above 1 becomes 1:
result = x.clamp(min=0.0, max=1.0)
print(result)

tensor([0.0000, 0.0000, 0.0000, 0.5000, 1.0000, 1.0000])


##### Broadcasting

In [45]:
t1 = torch.tensor([[[1,2,3],[3,4,5]], [[3,7,3],[0,4,2]]])
print(t1.shape)

t2 = torch.tensor([[2,3,6]])
print(t2.shape)

t = t1+t2 
print(t)
print(t.shape)

torch.Size([2, 2, 3])
torch.Size([1, 3])
tensor([[[ 3,  5,  9],
         [ 5,  7, 11]],

        [[ 5, 10,  9],
         [ 2,  7,  8]]])
torch.Size([2, 2, 3])


In [51]:
# slice
x = torch.randint(1, 33, (3,4))
print(x)
view_slice = x[:, 1]
print(view_slice)
view_slice.fill_(5.0)
print(x)

tensor([[18, 11,  5,  6],
        [28, 20,  4, 28],
        [ 4, 24,  9, 30]])
tensor([11, 20, 24])
tensor([[18,  5,  5,  6],
        [28,  5,  4, 28],
        [ 4,  5,  9, 30]])


In [64]:
t = torch.randint(2, 9, (3,5))
cpy = t[torch.tensor([0, 1])]
print(t)
print(cpy)

tensor([[7, 2, 6, 3, 4],
        [3, 7, 4, 8, 8],
        [7, 5, 5, 7, 5]])
tensor([[7, 2, 6, 3, 4],
        [3, 7, 4, 8, 8]])


In [ ]:
# gather, scattter_ for getting/writting values inside tensors 